stages:
  - build

.job:build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login --username $DOCTL_API -p $DOCTL_API registry.digitalocean.com
  script:
    - export PACKAGE_VERSION=$(jq -r .version package.json)
    - echo "Building image $PACKAGE_VERSION..."
    - docker build -t $IMAGE_NAME:$TAG-latest .
    - echo "Tagging image..."
    - docker tag $IMAGE_NAME:$TAG-latest $IMAGE_NAME:$TAG-$PACKAGE_VERSION
    - echo "Pushing image..."
    - docker push $IMAGE_NAME:$TAG-latest

dev:build:
  variables:
    TAG: dev
    IMAGE_NAME: registry.digitalocean.com/propbar/automated-valuation-model
  extends: .job:build
  environment:
    name: dev
    url: https://dev-api.pbrouter.com/avm
  only:
    refs:
      - "develop"

prod:build:
  variables:
    TAG: prod
    IMAGE_NAME: registry.digitalocean.com/propbar/automated-valuation-model
  extends: .job:build
  environment:
    name: prod
    url: https://api.propbar.com/avm
  only:
    refs:
      - "master"
